### ISSUE TITLE
Remove this.template in app/index.js

### ISSUE THREAD

**Issue by fdelbrayelle** [jhipster/generator-jhipster-module#107]
This block of code should be removed from app/index.js as copyTpl no longer exist?

```
        this.template = function (source, destination) {
            this.fs.copyTpl(
                this.templatePath(source),
                this.destinationPath(destination),
                this
            );
        };
```

Modules should use instead the base generator `template` function:

```
    /**
     * Utility function to copy and process templates.
     *
     * @param {string} source - source
     * @param {string} destination - destination
     * @param {*} generator - reference to the generator
     * @param {*} options - options object
     * @param {*} context - context
     */
    template(source, destination, generator, options = {}, context) {
        const _this = generator || this;
        const _context = context || _this;
        jhipsterUtils.renderContent(source, _this, _context, options, res => {
            _this.fs.write(_this.destinationPath(destination), res);
        });
    }
```

**Comment by mshima** [comment]
It's there
https://github.com/SBoudrias/mem-fs-editor/#copytplfrom-to-context-templateoptions--copyoptions

**Comment by murdos** [comment]
And `generator-jhipster-module` has not dependency on `generator-jhipster`, only on yeoman

**Comment by fdelbrayelle** [comment]
I mean, modules generated through the module generator have this piece of code :

```
        this.template = function (source, destination) {
            this.fs.copyTpl(
                this.templatePath(source),
                this.destinationPath(destination),
                this
            );
        };
```

And such modules (like the [Kafka one](https://github.com/fdelbrayelle/generator-jhipster-kafka/)) actually use this.template from the generator so maybe it should be removed for the generated module, don't you think?

In addition, IDE clearly indicate that this.fs.copyTpl doesn't exist for this `fs` version in the generated module.

**Comment by mshima** [comment]
Can be removed if we document to use the yeoman upstream version.
https://yeoman.github.io/generator/Generator.html#renderTemplate
It was added recently.

But notice that the last parameter `this`, is passing the generator as data for the ejs template.
The upstream version uses `this.config.getAll()` by default for the data.

So the replacement would be `this.renderTemplate(source, destination, this);`.
Or override _templateData using `_templateData() { return this; }` implementation.

> I mean, modules generated through the module generator have this piece of code :
> 
> ```
>         this.template = function (source, destination) {
>             this.fs.copyTpl(
>                 this.templatePath(source),
>                 this.destinationPath(destination),
>                 this
>             );
>         };
> ```
> 
> And such modules (like the [Kafka one](https://github.com/fdelbrayelle/generator-jhipster-kafka/)) actually use this.template from the generator so maybe it should be removed for the generated module, don't you think?
> 
> In addition, IDE clearly indicate that this.fs.copyTpl doesn't exist for this `fs` version in the generated module.

I don't think IDE knows what is the type of this.fs, unless you are using typescript.
If you are using typescript, there is a bug in the typescript type definition.

Overall, `this.template` is a minor change and the yeoman docs is lacking an update.
So I think we should keep this way.

**Comment by fdelbrayelle** [comment]
I agree with you to keep this way before having more information.

Maybe the issue can remain in stand-by for this reason?

**Comment by pascalgrimaud** [comment]
@fdelbrayelle : what is the state of this ticket ? Should we close it ? Or is there someting to do ?

**Comment by fdelbrayelle** [comment]
The discussion didn't go further so it can be close IMO.
