### ISSUE TITLE
jhipsterVar is not read during npm/yarn test

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster-module#17]
##### **Overview of the issue**

When generating a new module, it's hard to write test because `yeoman-test`'s `RunContext.withGenerators` ignores `composeWith()`. Because of this, when running `npm test`, the `jhipsterVar` object doesn't get the properties it should have.

The old hack doesn't work anymore:
```javascript
this.composeWith('jhipster:modules',
    { jhipsterVar, jhipsterFunc },
    this.options.testmode ? { local: require.resolve('generator-jhipster/generators/modules') } : null
);
```

Nothing special I can do here, or maybe try to fix directly in [yeoman-test](https://github.com/yeoman/yeoman-test/) project

##### **Reproduce the error**

To reproduce, simply add: `console.dir(jhipsterVar);` in a test file.
Then run test. You will see that `jhipsterVar` contains only `moduleName`, instead of having full config from `.yo-rc.json` and other vars:

```yaml
{ moduleName: 'helloworld' }
```

##### **Related issues**

Current issue: https://github.com/yeoman/yeoman-test/issues/16
Original issue: https://github.com/yeoman/generator/issues/704
Found by @bastienmichaux : https://github.com/bastienmichaux/generator-jhipster-db-helper/issues/19

**Comment by bastienmichaux** [comment]
A quick fix can be writing a polyfill for jhipsterVar and jhipsterFunc, then check for undefined values. We [did one](https://github.com/bastienmichaux/generator-jhipster-db-helper/blob/f16b50114b6c72314914f5694f4380bd5585a0d2/generators/app/index.js#L31-L64) for our module.

**Comment by pascalgrimaud** [comment]
Interesting @bastienmichaux !
So you found a solution :)

**Comment by AdrienHorgnies** [comment]
Yeah, that's a solution but it would be much cleaner to have **jhipster-module** to work in testing environment.

**Comment by pascalgrimaud** [comment]
Fixed by https://github.com/jhipster/generator-jhipster-module/commit/a6efe65f12bb221dbddc0e5d5c489686573c2a52
