### ISSUE TITLE
Update the module template to Yeoman 2.0 style as done in JHipster.

### ISSUE THREAD

**Issue by CarreraPHP** [jhipster/generator-jhipster-module#18]
@deepu105, please update the module template to Yeoman 2.0 style as done in JHipster.

**Comment by deepu105** [comment]
This is in the pipeline cc @pascalgrimaud

**Comment by pascalgrimaud** [comment]
Yes, will do it when possible

**Comment by pascalgrimaud** [comment]
(just for me)
Related to this commit: https://github.com/jhipster/generator-jhipster/commit/61852253fd9e3c8b18318c684942f8d48475aa39#commitcomment-24526199

**Comment by CarreraPHP** [comment]
@deepu105  @pascalgrimaud , I have migrated the code to Yeoman 2.0 class based coding style. With the changes, I am able to generator a JHipster-module and the app hook is working fine. However, when trying to run an entity generator based on the entity hook, the code is failing with error **"This sub generator should be used only from JHipster and cannot be run directly..."**.

This error is triggered from the condition in index.js inside entity folder
```javascript
validate() {
    // this shouldn't be run directly
   if (!this.entityConfig) {
       this.env.error(chalk.red.bold('ERROR!') + ' This sub generator should be used only from JHipster and cannot be run directly...\n');
   }
}
```

can you explain me, why this ```enttiyConfig``` value is not there in my generator? also while analyzing the callHook method in 'generator-base' file, it seems the ```enttiyConfig``` is passed as a option in ```composeWith``` yeoman method. So i tried ```this.options.entityConfig``` instead, this resolves the error but nothing is happening.

I believe there is something very small that i am missing here, can u please help out on it.

Regards,
CarreraPHP

**Comment by CarreraPHP** [comment]
The ```this.options.entityConfig``` fixes the issue. 

On second time, when i tried the ```jhi-hook.json``` file inside ```.jhipster\modules``` folder was missing.
