### ISSUE TITLE
Remove Gulp

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster-module#20]
As suggested by @deepu105, it's not necessary to keep Gulp here.
Let remove it, and add task to package.json

We can follow this: https://github.com/hipster-labs/generator-jhipster-entity-audit/commit/fce0a916692637700be8dcf0c71f875f31d17b6d

**Comment by deepu105** [comment]
yes the below will do the job
```
release": "git push && git push --tags && npm publish",
     "release:patch": "npm version patch -a -m \"Update to %s\" && npm run release",
     "release:minor": "npm version minor -a -m \"Update to %s\" && npm run release",
     "release:major": "npm version major -a -m \"Update to %s\" && npm run release"
```
