### ISSUE TITLE
GitHub username does not work with generator

### ISSUE THREAD

**Issue by Flying-Bison** [jhipster/generator-jhipster-module#22]
My GitHub username does not work while answering the prompts for the yo jhipster-module command.

During question this occurs:
What is your GitHub username? Flying-Bison
>> Your username is mandatory, cannot contain special characters or a blank space.

If I try an alternate name with an underscore it works
What is your GitHub username? Flying_Bison

However, this is an illegal name according to GitHub. I tried to change my username to this and it gave an error message:
"Login may only contain alphanumeric characters or single hyphens, and cannot begin or end with a hyphen"

Therefore, this appears to be a bug with the generator's validation rules on this question. 
Flying_Bison should not be allowed while Flying-Bison should be according to GitHub's error message.

**Comment by pascalgrimaud** [comment]
You're right.
The regex need to be changed here: https://github.com/jhipster/generator-jhipster-module/blob/master/generators/app/index.js#L84

**Comment by Flying-Bison** [comment]
I was gonna make a pull request to modify the regex. I'll submit it in a short bit here. I just got back to my computer after lunch.

**Comment by pascalgrimaud** [comment]
thanks a lot!
I could do a new release after your PR

**Comment by Flying-Bison** [comment]
@pascalgrimaud I may misunderstanding this entirely, however I don't seem to be able to push a branch up so that I can make a pull request. I am very new to working in actual GitHub so I may be missing something. Is there a different way to start a PR without pushing a branch first?

**Comment by ruddell** [comment]
@Flying-Bison You should fork the repository first, add this one as the `upstream` remote, then create a branch on your fork with your changes.  A full guide can be seen in the [generator's Contributing docs](https://github.com/jhipster/generator-jhipster/blob/29506a7976d474bbabdb46e8eda1adeac9fe43f4/CONTRIBUTING.md#submitting-a-pull-request)

**Comment by Flying-Bison** [comment]
@ruddell Thanks for the information. That makes a lot more sense than the way I was trying to do that. 

I think the PR should be requested correctly now. I was unsure if I was allowed to make one of the modifications that I made. However, I really wanted to be able to provide unit tests for the method I modified. To do this I needed to extract the methods out of index.js.

**Comment by MandeepSinghLopo** [comment]
erroe
