### ISSUE TITLE
Test error on windows

### ISSUE THREAD

**Issue by amanganiello90** [jhipster/generator-jhipster-module#24]
The test script generated from the 2.4.0 yeoman generator version is wrong for windows: 

```javascript
 "test": "mocha test/*"
```
The error run is: 

```
Error: Cannot find module '..\test\templates'
```

Maybe you have to change in:

```javascript
 "test": "mocha test"
```
The last works for every system platform.

**Comment by ruddell** [comment]
Thank you for the report, would you like to create a pull request fixing the issue?

**Comment by amanganiello90** [comment]
Ok, I will contribute for it. I'm a frontend and DevOps specialist and I can help you in jhipster's growth. Could you add me in the jhipster organization? Thanks

**Comment by amanganiello90** [comment]
thanks a lot, I will provide the PR

**Comment by pascalgrimaud** [comment]
closing as the PR was merged
I'll try to do a release this weekend
