### ISSUE TITLE
Migrate CI to GitHub actions

### ISSUE THREAD

**Issue by cbornet** [jhipster/generator-jhipster-module#49]

**Comment by pascalgrimaud** [comment]
Related to https://github.com/jhipster/generator-jhipster/issues/10817
+1 !

**Comment by cbornet** [comment]
This could also be done for the generated module

**Comment by cbornet** [comment]
Example of GH action for generated module : https://github.com/cbornet/generator-jhipster-pulsar/blob/master/.github/workflows/github-ci.yml
* unit tests of the module
* integration tests with a matrix build of app configs (maven and gradle) against the latest JHipster version
