### ISSUE TITLE
.gitignore template not published with the npm package

### ISSUE THREAD

**Issue by amanganiello90** [jhipster/generator-jhipster-module#67]
Hi all,
I used the 2.6.0 version, and it raises an error after prompting phase because it is missed the .gitignore tamplate in the package: https://github.com/jhipster/generator-jhipster-module/blob/v2.6.0/generators/app/templates/.gitignore

The reason is that in the npm publishing is been ignored that file.

**Comment by ecostanzi** [comment]
Hi @amanganiello90, probably renaming the template to `.gitignore.ejs` and fixing the `index.js` accordingly should be enough to fix the issue. I saw you already contributed to this module would you like to do a PR?

**Comment by amanganiello90** [comment]
Yes, for me it's not a problem, I'm contributing a various jhipster projests.
